name: CI/CD Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.8.0

    - name: Login Docker
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker Images
      uses: docker/build-push-action@v5.0.0
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          mateusnosse/cicd:latest
          mateusnosse/cicd:v${{ github.run_number }}

  CD-AZURE:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no Azure
        uses: Azure/webapps-deploy@v2.2.11
        with:
          app-name: cicd-julio-mateus
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: mateusnosse/cicd:v${{ github.run_number }}

  CD-Render:
    needs: [ CI ]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to Render
        uses:  johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
